#================================================================================================================================================
# You should be able to use any of the values you can find here: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#================================================================================================================================================
backendImage:
  repository: yooooomi/your_spotify_server
  pullPolicy: IfNotPresent
  tag: 1.17.0

frontendImage:
  repository: yooooomi/your_spotify_client
  pullPolicy: IfNotPresent
  tag: 1.17.0

service:
  main:
    enabled: false
  backend:
    controller: backend
    ports:
      backend:
        port: 8080
  frontend:
    controller: frontend
    ports:
      frontend:
        port: 3000

#=============================
# Application-specific config
#=============================
yourSpotify:
  configSecret:
    existingSecret: ""

  spotifyPublic: ""
  spotifyPrivate: ""

  mongodbPassword: "admin"

#=============
# Subchart(s)
#=============
mongodb:
  enabled: true
