persistence:
  config:
    enabled: true
    size: 2Gi
  books:
    enabled: true
    type: hostPath
    mountPath: /books
    hostPath: /storagePool/Books/ebooks

nodeSelector:
  kubernetes.io/hostname: gaming-pc-node
