lidarr:
  urlBase: lidarr

  configSecret:
    existingSecret: lidarr-config-secret

  externalAuth: true

  postgres:
    enabled: false
    setupJob:
      enabled: false

serviceAccount:
  create: true
  name: lidarr
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"

persistence:
  music:
    enabled: true
    type: hostPath
    mountPath: /music
    hostPath: /storagePool/videoData/Music
  downloads:
    enabled: true
    type: hostPath
    mountPath: /downloads
    hostPath: /storagePool/videoData/downloads
