env: prod-cluster

hostnames:
  - prod-cluster-lb.lan
  - 192.168.86.3

gitRevision: master

flaresolverr:
  enabled: true

hashi-vault:
  enabled: true
  configuration:
    enabled: true
  dependentApps:
    vault-secrets-operator:
      configuration:
        enabled: true

istio:
  enabled: true

it-tools:
  enabled: true

job-templates:
  enabled: true

jellyfin:
  enabled: true
  configuration:
    enabled: true

jellyseerr:
  enabled: true
  configuration:
    enabled: true

kyverno:
  enabled: true

longhorn:
  enabled: true
  configuration:
    enabled: true

lidarr:
  enabled: true
  configuration:
    enabled: true

metallb:
  enabled: true
  dependentApps:
    metallb-config:
      configuration:
        enabled: true

navidrome:
  enabled: true
  configuration:
    enabled: true

postgres:
  enabled: true

prowlarr:
  enabled: true
  configuration:
    enabled: true

radarr:
  enabled: true
  configuration:
    enabled: true

sonarr:
  enabled: true
  configuration:
    enabled: true

transmission:
  enabled: true
  configuration:
    enabled: true

video-stack-configuration:
  enabled: true
  configuration:
    enabled: true

your-spotify:
  enabled: true
  configuration:
    enabled: true
