persistence:
  data:
    accessMode: ReadWriteOnce
    enabled: true
    size: 2Gi
  music:
    enabled: true
    type: hostPath
    mountPath: /music
    hostPath: /storagePool/videoData/Music

navidrome:
  baseUrl: /music
