radarr:
  urlBase: radarr

  configSecret:
    existingSecret: radarr-config-secret

  externalAuth: true

  postgres:
    enabled: true
    setupJob:
      enabled: false

serviceAccount:
  create: true
  name: radarr
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"

persistence:
  videos:
    enabled: true
    type: hostPath
    mountPath: /videos
    hostPath: /storagePool/videoData/Videos/
  downloads:
    enabled: true
    type: hostPath
    mountPath: /downloads
    hostPath: /storagePool/videoData/downloads

initContainers:
  init-tv-dir:
    image: busybox
    command: ["sh", "-c"]
    args:
      - |
        mkdir -p /videos/Movies
        chmod 777 /videos/Movies
        chown -R 911 /videos/Movies
    volumeMounts:
      - name: videos
        mountPath: /videos

nodeSelector:
  kubernetes.io/hostname: gaming-pc-node
