romm:
  configSecret: romm-config-secret

  database:
    enabled: true

redis:
  auth:
    existingSecret: romm-config-secret
    existingSecretPasswordKey: redisPassword

env:
  HASHEOUS_API_ENABLED: true
  STEAMGRIDDB_API_KEY:
    valueFrom:
      secretKeyRef:
        name: romm-config-secret
        key: steamGridDBApiKey

serviceAccount:
  create: true
  name: romm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
