romm:
  configSecret: romm-config-secret

  database:
    enabled: true

redis:
  auth:
    existingSecret: romm-config-secret
    existingSecretPasswordKey: redisPassword

env:
  ROMM_BASE_PATH: /romm

serviceAccount:
  create: true
  name: romm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
