romm:
  configSecret: romm-config-secret

  database:
    enabled: true

redis:
  auth:
    existingSecret: romm-config-secret
    existingSecretPasswordKey: redisPassword

env:
  HASHEOUS_API_ENABLED: true
  STEAMGRIDDB_API_KEY:
    valueFrom:
      secretKeyRef:
        name: romm-config-secret
        key: steamGridDBApiKey
  RETROACHIEVEMENTS_API_KEY:
    valueFrom:
      secretKeyRef:
        name: romm-config-secret
        key: retroAchievementsApiKey

persistence:
  romm:
    enabled: true
    type: hostPath
    mountPath: /romm
    hostPath: /storagePool/romm

serviceAccount:
  create: true
  name: romm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"

nodeSelector:
  kubernetes.io/hostname: gaming-pc-node
