{{- include "bjw-s.common.loader.init" . }}

{{/* Append the hardcoded settings */}}
{{- define "navidrome.harcodedValues" -}}
env:
  - name: ND_BASEURL
    value: {{ .Values.navidrome.baseUrl }}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "navidrome.harcodedValues" . | fromYaml) -}}
{{ include "bjw-s.common.loader.generate" . }}