hostnames:
  - localhost

argocd:
  # This breaks the rule we have going here, BUT, if you're running this,
  # it's probably with ArgoCD, so we should be able to access it no matter
  # what
  enabled: true
  prefixes:
    - /argocd
  group: "Cluster Management"
  icon: argocd.png
  nameOverride: ArgoCD
  description: Deployment management for all mah stuff
audiobookshelf:
  enabled: false
  prefixes:
    - /audiobookshelf
  group: "Books and Reading"
bentopdf:
  enabled: false
  subdomain: bento
  group: "Tools and Utilities"
calibre-web:
  enabled: false
  prefixes:
    - /calibre-web
  group: "Books and Reading"
flashpaper:
  enabled: false
  subdomain: ots
  group: "Tools and Utilities"
grafana:
  enabled: false
  prefixes:
    - /grafana
    - /grafana/
  group: "Cluster Management"
hashi-vault:
  enabled: false
  subdomain: vault
  group: "Cluster Management"
it-tools:
  enabled: false
  prefixes:
    - /it-tools/
    - /it-tools
  group: "Tools and Utilities"
jellyfin:
  enabled: false
  prefixes:
    - /emby
  group: "Videos"
jellyseerr:
  enabled: false
  subdomain: jellyseerr
  group: "Videos"
kiali:
  enabled: false
  prefixes:
    - /kiali
  group: "Cluster Management"
lidarr:
  enabled: false
  prefixes:
    - /lidarr
  group: "Music"
longhorn:
  enabled: false
  prefixes:
    - /longhorn/
  group: "Cluster Management"
navidrome:
  enabled: false
  prefixes:
    - /music
  group: Music
paperless:
  enabled: false
  prefixes:
    - /paperless
  group: "Personal Management"
prowlarr:
  enabled: false
  prefixes:
    - /prowlarr
  group: "Download Management"
radarr:
  enabled: false
  prefixes:
    - /radarr
  group: Videos
sonarr:
  enabled: false
  prefixes:
    - /sonarr
  group: Videos
transmission:
  enabled: false
  prefixes:
    - /transmission
  group: "Download Management"
your-spotify:
  enabled: false
  subdomain: spotify
  group: "Personal Management"
