apiVersion: v2
name: it-tools
description: A Helm chart for installing and managing it-tools. Based on the bjw-s library chart

type: application

version: 0.0.3

appVersion: "2.0.5"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 1.5.1
