{{- include "bjw-s.common.loader.init" . }}

{{/* Append the hardcoded settings */}}
{{- define "$CHART_NAME.harcodedValues" -}}


{{- end -}}
{{- $UNDERSCORE := mergeOverwrite .Values (include "$CHART_NAME.harcodedValues" . | fromYaml) -}}
{{ include "bjw-s.common.loader.generate" . }}