hostnames:
  - localhost

argocd:
  # This breaks the rule we have going here, BUT, if you're running this,
  # it's probably with ArgoCD, so we should be able to access it no matter
  # what
  enabled: true
  prefixes:
    - /argocd
  destinationSvc: argocd-server.argocd.svc.cluster.local
audiobookshelf:
  enabled: false
  prefixes:
    - /audiobookshelf
  destinationSvc: audiobookshelf.books.svc.cluster.local
bar-assistant:
  enabled: false
  subdomain: bar
  destinationSvc: bar-assistant-frontend.inventory-mgmt.svc.cluster.local
  dependentIngresses:
    bar-assistant-api:
      enabled: true
      subdomain: bar-assistant-api
      destinationSvc: bar-assistant-backend.inventory-mgmt.svc.cluster.local
bentopdf:
  enabled: false
  subdomain: bento
  destinationSvc: bentopdf.misc.svc.cluster.local
  destinationPort: 8080
calibre-web:
  enabled: false
  prefixes:
    - /calibre-web
  destinationSvc: calibre-web.books.svc.cluster.local
  headers:
    request:
      add:
        X-Script-Name: /calibre-web
# TODO Migrate this to istio
crafty-server:
  enabled: false
firefly-iii:
  enabled: false
  subdomain: firefly
  destinationSvc: firefly-iii.finance.svc.cluster.local
  dependentIngresses:
    firefly-iii-data-importer:
      enabled: true
      subdomain: firefly-importer
      destinationSvc: firefly-iii-importer.finance.svc.cluster.local
flashpaper:
  enabled: false
  subdomain: ots
  destinationSvc: flashpaper.misc.svc.cluster.local
grafana:
  enabled: false
  prefixes:
    - /grafana
    - /grafana/
  rewrite:
    uri: /
  destinationSvc: prometheus-grafana.monitoring.svc.cluster.local
hashi-vault:
  enabled: false
  subdomain: vault
  destinationSvc: hashi-vault.vault.svc.cluster.local
  destinationPort: 8200
homepage:
  multiHost: true
  enabled: false
  prefixes:
    - /
  destinationSvc: homepage.misc.svc.cluster.local
  destinationPort: 3000
it-tools:
  enabled: false
  prefixes:
    - /it-tools/
    - /it-tools
  destinationSvc: it-tools.misc.svc.cluster.local
jellyfin:
  enabled: false
  prefixes:
    - /emby
  destinationSvc: jellyfin.videos.svc.cluster.local
jellyseerr:
  enabled: false
  subdomain: jellyseerr
  destinationSvc: jellyseerr.videos.svc.cluster.local
kiali:
  enabled: false
  prefixes:
    - /kiali
  destinationSvc: kiali.istio-system.svc.cluster.local
  destinationPort: 20001
lidarr:
  enabled: false
  prefixes:
    - /lidarr
  destinationSvc: lidarr.music.svc.cluster.local
longhorn:
  enabled: false
  prefixes:
    - /longhorn/
  rewrite:
    uri: /
  destinationSvc: longhorn-frontend.longhorn-system.svc.cluster.local
n8n:
  enabled: false
  subdomain: n8n
  destinationSvc: n8n.n8n.svc.cluster.local
navidrome:
  enabled: false
  prefixes:
    - /music
  destinationSvc: navidrome.music.svc.cluster.local
paperless:
  enabled: false
  prefixes:
    - /paperless
  destinationSvc: paperless-paperless-ngx.paperless.svc.cluster.local
  destinationPort: 8000
prowlarr:
  enabled: false
  prefixes:
    - /prowlarr
  destinationSvc: prowlarr.videos.svc.cluster.local
radarr:
  enabled: false
  prefixes:
    - /radarr
  destinationSvc: radarr.videos.svc.cluster.local
sonarr:
  enabled: false
  prefixes:
    - /sonarr
  destinationSvc: sonarr.videos.svc.cluster.local
transmission:
  enabled: false
  prefixes:
    - /transmission
  destinationSvc: transmission.videos.svc.cluster.local
your-spotify:
  enabled: false
  subdomain: spotify
  destinationSvc: your-spotify-frontend.your-spotify.svc.cluster.local
  destinationPort: "3000"
  dependentIngresses:
    your-spotify-api:
      enabled: true
      subdomain: spotify-api
      destinationSvc: your-spotify-backend.your-spotify.svc.cluster.local
      destinationPort: "8080"
