qa-cluster:
  enabled: false
  roles:
    - prowlarr
  databases:
    prowlarr-main:
      dbName: prowlarr_main
      owner: prowlarr
    prowlarr-logs:
      dbName: prowlarr_logs
      owner: prowlarr
  storage: 1Gi
