qa-cluster:
  enabled: false
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  image: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  roles:
    - prowlarr
    - sonarr
    - radarr
    - paperless
    - lidarr
    - n8n
    - firefly-iii
    - romm
    - immich
  databases:
    prowlarr-main:
      dbName: prowlarr_main
      owner: prowlarr
    prowlarr-logs:
      dbName: prowlarr_logs
      owner: prowlarr
    sonarr-main:
      dbName: sonarr_main
      owner: sonarr
    sonarr-logs:
      dbName: sonarr_logs
      owner: sonarr
    radarr-main:
      dbName: radarr_main
      owner: radarr
    radarr-logs:
      dbName: radarr_logs
      owner: radarr
    paperless:
      owner: paperless
    lidarr-main:
      dbName: lidarr_main
      owner: lidarr
    lidarr-logs:
      dbName: lidarr_logs
      owner: lidarr
    n8n:
      owner: n8n
    firefly:
      owner: firefly-iii
    romm:
      owner: romm
    immich:
      owner: immich
      extensions:
        - name: vchord
        - name: earthdistance
        - name: vector
        - name: cube
  storage: 1Gi
staging-cluster:
  enabled: false
  roles:
    - prowlarr
    - sonarr
    - radarr
    - paperless
    - lidarr
    - n8n
    - firefly-iii
    - romm
  databases:
    prowlarr-main:
      dbName: prowlarr_main
      owner: prowlarr
    prowlarr-logs:
      dbName: prowlarr_logs
      owner: prowlarr
    sonarr-main:
      dbName: sonarr_main
      owner: sonarr
    sonarr-logs:
      dbName: sonarr_logs
      owner: sonarr
    radarr-main:
      dbName: radarr_main
      owner: radarr
    radarr-logs:
      dbName: radarr_logs
      owner: radarr
    paperless:
      owner: paperless
    lidarr-main:
      dbName: lidarr_main
      owner: lidarr
    lidarr-logs:
      dbName: lidarr_logs
      owner: lidarr
    n8n:
      owner: n8n
    firefly:
      owner: firefly
    romm:
      owner: romm
  storage: 1Gi
prod-cluster:
  enabled: false
  replicas: 2
  roles:
    - prowlarr
    - sonarr
    - radarr
    - paperless
    - lidarr
    - n8n
    - firefly-iii
    - romm
  databases:
    prowlarr-main:
      dbName: prowlarr_main
      owner: prowlarr
    prowlarr-logs:
      dbName: prowlarr_logs
      owner: prowlarr
    sonarr-main:
      dbName: sonarr_main
      owner: sonarr
    sonarr-logs:
      dbName: sonarr_logs
      owner: sonarr
    radarr-main:
      dbName: radarr_main
      owner: radarr
    radarr-logs:
      dbName: radarr_logs
      owner: radarr
    paperless:
      owner: paperless
    lidarr-main:
      dbName: lidarr_main
      owner: lidarr
    lidarr-logs:
      dbName: lidarr_logs
      owner: lidarr
    n8n:
      owner: n8n
    firefly:
      owner: firefly-iii
    romm:
      owner: romm
  storage: 50Gi
