{{- include "bjw-s.common.loader.init" . }}

# {{/* Append the hardcoded settings */}}
# {{- define "calibre-web.harcodedValues" -}}


# {{- end -}}
# {{- $_ := mergeOverwrite .Values (include "calibre-web.harcodedValues" . | fromYaml) -}}
{{ include "bjw-s.common.loader.generate" . }}