env: external-user-1-cluster

hostnames:
  - 192.168.86.41

gitRevision: feat/external-user-1-final-retry

flaresolverr:
  enabled: true

hashi-vault:
  enabled: true
  configuration:
    enabled: true
  dependentApps:
    vault-secrets-operator:
      configuration:
        enabled: true

istio:
  enabled: true
  dependentApps:
    kiali:
      enabled: false

jellyfin:
  enabled: true
  configuration:
    enabled: true

jellyseerr:
  enabled: false
  configuration:
    enabled: true

longhorn:
  enabled: true
  configuration:
    enabled: true

metallb:
  enabled: true
  dependentApps:
    metallb-config:
      configuration:
        enabled: true

prowlarr:
  enabled: true
  configuration:
    enabled: true

radarr:
  enabled: true
  configuration:
    enabled: true

sonarr:
  enabled: true
  configuration:
    enabled: true

transmission:
  enabled: true
  configuration:
    enabled: true

video-stack-configuration:
  enabled: true
  configuration:
    enabled: true
