env: external-user-1-cluster

hostnames:
  - 192.168.86.41

gitRevision: feat/external-user-1-final-retry

flaresolverr:
  enabled: true

hashi-vault:
  enabled: true
  configuration:
    enabled: true
  dependentApps:
    vault-secrets-operator:
      configuration:
        enabled: true

istio:
  enabled: true
  dependentApps:
    kiali:
      enabled: false

jellyfin:
  enabled: true
  configuration:
    enabled: true

jellyseerr:
  enabled: false
  configuration:
    enabled: true

longhorn:
  enabled: true
  configuration:
    enabled: true

metallb:
  enabled: true
  dependentApps:
    metallb-config:
      configuration:
        enabled: true

prowlarr:
  enabled: true
  configuration:
    enabled: true

radarr:
  enabled: true
  configuration:
    enabled: true

sonarr:
  enabled: true
  configuration:
    enabled: true

transmission:
  enabled: true
  configuration:
    enabled: true

video-stack-configuration:
  enabled: true
  secureValues: |
    prowlarr:
      port: 80
      urlBase: /prowlarr
      apiKey: <path:argocd/data/video_stack_configuration#prowlarrApiKey>

    radarr:
      port: 80
      urlBase: /radarr
      apiKey: <path:argocd/data/video_stack_configuration#radarrApiKey>
      rootFolders:
        - /videos/Movies

    sonarr:
      port: 80
      urlBase: /sonarr
      apiKey: <path:argocd/data/video_stack_configuration#sonarrApiKey>
      rootFolders:
        - /videos/TV

    lidarr:
      enabled: false
      port: 80
      urlBase: /lidarr
      apiKey: <path:argocd/data/video_stack_configuration#lidarrApiKey>

    jellyseerr:
      hostname: jellyseerr
      urlBase: /
      port: 80
      apiKey: <path:argocd/data/video_stack_configuration#jellyseerrApiKey>
      jellyfin:
        hostname: jellyfin
        url_base: /emby
        port: 80
        username: <path:argocd/data/video_stack_configuration#jellyfinUsername>
        password: <path:argocd/data/video_stack_configuration#jellyfinPassword>
        emailAddress: <path:argocd/data/video_stack_configuration#jellyfinEmail>

    transmission:
      port: 80
