env: external-user-1-cluster

gitRevision: feat/external-user-1-final-retry

longhorn:
  enabled: true
  configuration:
    enabled: true

flaresolverr:
  enabled: true

hashi-vault:
  enabled: true
  configuration:
    enabled: true

jellyfin:
  enabled: true
  configuration:
    enabled: true

jellyseerr:
  enabled: true
  configuration:
    enabled: true

prowlarr:
  enabled: true
  configuration:
    enabled: true

radarr:
  enabled: true
  configuration:
    enabled: true

sonarr:
  enabled: true
  configuration:
    enabled: true

transmission:
  enabled: true
  configuration:
    enabled: true

video-stack-configuration:
  enabled: true
  configuration:
    enabled: true
