radarr:
  urlBase: radarr

  configSecret:
    existingSecret: radarr-config-secret

  externalAuth: true

serviceAccount:
  create: true
  name: radarr
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"

persistence:
  config:
    enabled: true
  videos:
    enabled: true
    type: hostPath
    mountPath: /videos
    hostPath: /externalStorage/Media
  downloads:
    enabled: true
    type: hostPath
    mountPath: /downloads
    hostPath: /externalStorage/Media/downloads

initContainers:
  init-tv-dir:
    image: busybox
    command: ["sh", "-c"]
    args:
      - |
        mkdir -p /videos/Movies
        chmod 777 /videos/Movies
        chown -R 911 /videos/Movies
    volumeMounts:
      - name: videos
        mountPath: /videos
