{{- include "bjw-s.common.loader.init" . }}

{{/* Append the hardcoded settings */}}
{{- define "blackcandy.harcodedValues" -}}
env:
  - name: MEDIA_PATH
    value: /media
  - name: SECRET_KEY_BASE
    value: {{ .Values.blackcandy.password }}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "blackcandy.harcodedValues" . | fromYaml) -}}
{{ include "bjw-s.common.loader.generate" . }}