apiVersion: v2
name: lidarr
description: A Helm chart for installing and managing lidarr. Based on the bjw-s library chart

type: application

version: 0.0.3

appVersion: "3.1.0"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 1.5.1
