{{- include "bjw-s.common.loader.init" . }}

{{/* Append the hardcoded settings */}}
{{- define "flashpaper.harcodedValues" -}}


{{- end -}}
{{- $_ := mergeOverwrite .Values (include "flashpaper.harcodedValues" . | fromYaml) -}}
{{ include "bjw-s.common.loader.generate" . }}