meilisearch:
  auth:
    existingMasterKey: bar-assistant-config-secret
  environment:
    MEILI_ENV: production

controllers:
  backend:
    type: deployment
    serviceAccount: bar-assistant
    containers:
      bar-assistant:
        env:
          MEILISEARCH_HOST: http://bar-assistant-meilisearch:7700
          CACHE_DRIVER: file
          SESSION_DRIVER: file
          MEILISEARCH_KEY:
            valueFrom:
              secretKeyRef:
                name: bar-assistant-config-secret
                key: MEILI_MASTER_KEY
  frontend:
    type: deployment
    containers:
      saltrim:
        env:
          API_URL: http://bar-assistant-api.qa-cluster-lb.lan
