env: qa-cluster

hostnames:
  - qa-cluster-lb.lan
  - "172.18.255.200"

gitRevision: project-appocalypse/your-spotify-fix

bar-assistant:
  enabled: false
  configuration:
    enabled: true

homepage:
  enabled: true

hashi-vault:
  enabled: true
  configuration:
    enabled: true
  dependentApps:
    vault-secrets-operator:
      configuration:
        enabled: true

metallb:
  enabled: true
  dependentApps:
    metallb-config:
      configuration:
        enabled: true

istio:
  enabled: true
  dependentApps:
    kiali:
      enabled: false

your-spotify:
  enabled: true
