env: qa-cluster

gitRevision: project-appocalypse/new-app-wrapper

flaresolverr:
  enabled: false

hashi-vault:
  enabled: true
  configuration:
    enabled: true
  dependentApps:
    vault-secrets-operator:
      configuration:
        enabled: true

jellyfin:
  enabled: false
  configuration:
    enabled: true

jellyseerr:
  enabled: false
  configuration:
    enabled: true

job-templates:
  enabled: false

postgres:
  enabled: true

prowlarr:
  enabled: false
  configuration:
    enabled: true

radarr:
  enabled: false
  configuration:
    enabled: true

sonarr:
  enabled: false
  configuration:
    enabled: true

transmission:
  enabled: false
  configuration:
    enabled: true

video-stack-configuration:
  enabled: false
  configuration:
    enabled: true

nginx:
  enabled: true
