env: qa-cluster

hostnames:
  - qa-cluster-lb.lan
  - "172.18.255.200"

gitRevision: master

homepage:
  enabled: true

flaresolverr:
  enabled: false

bentopdf:
  enabled: true

hashi-vault:
  enabled: true
  configuration:
    enabled: true
  dependentApps:
    vault-secrets-operator:
      configuration:
        enabled: true

jellyfin:
  enabled: false
  configuration:
    enabled: true

jellyseerr:
  enabled: false
  configuration:
    enabled: true

job-templates:
  enabled: false

postgres:
  enabled: false

prowlarr:
  enabled: false
  configuration:
    enabled: true

lidarr:
  enabled: false
  configuration:
    enabled: true

radarr:
  enabled: false
  configuration:
    enabled: true

sonarr:
  enabled: false
  configuration:
    enabled: true

transmission:
  enabled: false
  configuration:
    enabled: true

video-stack-configuration:
  enabled: false
  configuration:
    enabled: true

paperless:
  enabled: false
  configuration:
    enabled: true

metallb:
  enabled: true
  dependentApps:
    metallb-config:
      configuration:
        enabled: true

it-tools:
  enabled: false
  configuration:
    enabled: true

flashpaper:
  enabled: false

istio:
  enabled: true
  dependentApps:
    kiali:
      enabled: false
