env: qa-cluster

gitRevision: project-appocalypse/it-tools

flaresolverr:
  enabled: false

hashi-vault:
  enabled: true
  configuration:
    enabled: true
  dependentApps:
    vault-secrets-operator:
      configuration:
        enabled: true

jellyfin:
  enabled: false
  configuration:
    enabled: true

jellyseerr:
  enabled: false
  configuration:
    enabled: true

job-templates:
  enabled: false

postgres:
  enabled: true

prowlarr:
  enabled: false
  configuration:
    enabled: true

radarr:
  enabled: false
  configuration:
    enabled: true

sonarr:
  enabled: false
  configuration:
    enabled: true

transmission:
  enabled: false
  configuration:
    enabled: true

video-stack-configuration:
  enabled: false
  configuration:
    enabled: true

# nginx:
#   enabled: true

paperless:
  enabled: false
  configuration:
    enabled: true

metallb:
  enabled: false

it-tools:
  enabled: true
  dependentApps:
    metallb-config:
      configuration:
        enabled: true

istio:
  enabled: false
  dependentApps:
    kiali:
      enabled: false
