bar-assistant:
  enabled: false
  secretDestinationNamespace: inventory-mgmt
  destination:
    transformation:
      templates:
        MEILI_MASTER_KEY:
          text: "{{ .Secrets.meilisearchApiKey }}"
firefly-iii:
  enabled: false
  secretDestinationNamespace: finance
  postgresSecret:
    enabled: true
  serviceAccount:
    name: default
immich:
  enabled: false
  secretDestinationNamespace: immich
  postgresSecret:
    enabled: true
jellyfin:
  enabled: false
  secretDestinationNamespace: videos
jellyseerr:
  enabled: false
  secretDestinationNamespace: videos
lidarr:
  enabled: false
  secretDestinationNamespace: music
  postgresSecret:
    enabled: true
n8n-config:
  enabled: false
  secretDestinationNamespace: n8n
  postgresSecret:
    enabled: true
paperless:
  enabled: false
  secretDestinationNamespace: paperless
  serviceAccount:
    name: paperless-ngx
  postgresSecret:
    enabled: true
postgres:
  enabled: false
  secretDestinationNamespace: postgres
  destination:
    type: kubernetes.io/basic-auth
    labels:
      cnpg.io/reload: ""
  serviceAccount:
    name: postgres-cluster
prowlarr:
  enabled: false
  secretDestinationNamespace: videos
  postgresSecret:
    enabled: true
radarr:
  enabled: false
  secretDestinationNamespace: videos
  postgresSecret:
    enabled: true
romm:
  enabled: false
  secretDestinationNamespace: romm
  postgresSecret:
    enabled: true
sonarr:
  enabled: false
  secretDestinationNamespace: videos
  postgresSecret:
    enabled: true
transmission:
  enabled: false
  secretDestinationNamespace: videos
  resourceName: vpn
  serviceAccount:
    name: transmission
  destination:
    transformation:
      templates:
        vpnConfig:
          text: |
            {{ .Secrets.vpnConfig | replace "\\n" "\n" }}
video-stack-configuration:
  enabled: false
  secretDestinationNamespace: videos
  resourceName: setup-job
  serviceAccount:
    create: true
your-spotify:
  enabled: false
  secretDestinationNamespace: your-spotify
  mount: misc
  serviceAccount:
    name: default
