apiVersion: v2
name: romm
description: A Helm chart for installing and managing romm. Based on the bjw-s library chart

type: application

version: 0.0.3

appVersion: "4.5.0"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 1.5.1
  - name: redis
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.14.0
    condition: redis.enabled
